DROP TABLE spots, users, reports;

CREATE TABLE spots(
  ID SERIAL PRIMARY KEY,
  NUM INT,
  SECTION TEXT,
  OWNER_EMAIL TEXT,
  INUSE BOOLEAN,
  CURRENT_EMAIL TEXT
);

CREATE TABLE users(
  SESSION_TOKEN TEXT,
  EMAIL TEXT PRIMARY KEY,
  ACCESS INT,
  NAME TEXT,
  LICENSE_PlATE TEXT
);

CREATE TABLE reports(
  ID SERIAL PRIMARY KEY,
  AUTHOR_EMAIL TEXT,
  NOTE TEXT,
  SPOT_ID TEXT,
  LICENSE_PlATE TEXT,
  CREATION_DATE TEXT
);

INSERT INTO spots (NUM, SECTION, OWNER_EMAIL, INUSE, CURRENT_EMAIL) VALUES (1, 'AM', 'jonescal@bentonvillek12.org', true, 'jonescal@bentonvillek12.org');
INSERT INTO users VALUES ('', 'jonescal@bentonvillek12.org', 3, 'Caleb Jones', '123ABC');
INSERT INTO users VALUES ('', 'abc@bentonvillek12.org', 2, 'ABC Jones', '124ABC');
