DROP TABLE spots;
DROP TABLE users;
DROP TABLE reports;
DROP TABLE revokedTokens;
DROP TABLE ranges;
DROP TABLE schedule;

CREATE TABLE spots(
  ID SERIAL PRIMARY KEY,
  NAME TEXT,
  OWNER_EMAIL TEXT,
  INUSE BOOLEAN,
  CURRENT_EMAIL TEXT
);

CREATE TABLE users(
  EMAIL TEXT PRIMARY KEY,
  ACCESS INT,
  NAME TEXT,
  LICENSE_PlATE TEXT
);

CREATE TABLE reports(
  ID SERIAL PRIMARY KEY,
  AUTHOR_EMAIL TEXT,
  NOTE TEXT,
  SPOT_ID TEXT,
  LICENSE_PlATE TEXT,
  CREATION_DATE TEXT
);

CREATE TABLE revokedTokens(
  TOKEN_HASH TEXT PRIMARY KEY
);

CREATE TABLE ranges(
  EMAIL TEXT PRIMARY KEY,
  RANGE TEXT
);

CREATE TABLE schedule(
  ID SERIAL PRIMARY KEY,
  EMAIL TEXT,
  SID TEXT,
  ACTION TEXT,
  DAY TEXT
);

INSERT INTO users VALUES ('parkingdev@bentonvillek12.org', 3, 'DEVELOPER NOTAPERSON', 'ABC123');
